name: 280blocker

on:
  push:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 280blocker_adblock
        uses: wei/curl@master
        with:
          args: https://280blocker.net/files/280blocker_adblock_$(date +%Y%m).txt -o 280blocker_adblock.txt
      - name: 280blocker_domain_ag
        uses: wei/curl@master
        with:
          args: https://280blocker.net/files/280blocker_domain_ag_$(date +%Y%m).txt -o 280blocker_domain_ag.txt
      - name: push
        uses: actions-go/push@v1
        with:
          commit-files: 280blocker_adblock.txt, 280blocker_domain_ag.txt
          commit-message: ":rocket: Update"
